CREATE TABLE [dbo].[Users] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [Username]              NVARCHAR (MAX) NULL,
    [PasswordHash]          NVARCHAR (MAX) NULL,
    [PasswordSalt]          NVARCHAR (MAX) NULL,
    [Firstname]             NVARCHAR (MAX) NULL,
    [LastName]              NVARCHAR (MAX) NULL,
    [Age]                   INT            NOT NULL,
    [Sex]                   NVARCHAR (MAX) NULL,
    [Race]                  NVARCHAR (MAX) NULL,
    [Designation]           NVARCHAR (MAX) NULL,
    [JobTitle]              NVARCHAR (MAX) NULL,
    [SalaryLevel]           INT            NOT NULL,
    [ChiefDirectorate]      NVARCHAR (MAX) NULL,
    [Directorate]           NVARCHAR (MAX) NULL,
    [SubDirectorate]        NVARCHAR (MAX) NULL,
    [OfficeLocation]        NVARCHAR (MAX) NULL,
    [ContactNumberOffice]   NVARCHAR (MAX) NULL,
    [ContactCell]           NVARCHAR (MAX) NULL,
    [AppointmentDate]       NVARCHAR (MAX) NULL,
    [ProbationPeriodstatus] NVARCHAR (MAX) NULL,
    [InductionStatus]       NVARCHAR (MAX) NULL,
    [Manager]               NVARCHAR (MAX) NULL,
    [Highestqualification]  NVARCHAR (MAX) NULL,
    [HomeAddress]           NVARCHAR (MAX) NULL,
    [Maritalstatus]         NVARCHAR (MAX) NULL,
    [SpouseName]            NVARCHAR (MAX) NULL,
    [SpouseMaidenName]      NVARCHAR (MAX) NULL,
    [NextofKinName]         NVARCHAR (MAX) NULL,
    [NextofKinSurname]      NVARCHAR (MAX) NULL,
    [NextofKinRelation]     NVARCHAR (MAX) NULL,
    [Password]              NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
);

